name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      # Publish the site
      - name: Publish
        run: dotnet publish PersonalWebsite.sln -c Release -o release --nologo
      # changes the base-tag in index.html from '/' to 'PersonalWebsite' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to PersonalWebsite
        run: sed -i 's/<base href="\/" \/>/<base href="\/PersonalWebsite\/" \/>/g' realease/wwwroot/index.html

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      # Deploy the site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          force_orphan: true
